export const userInputs = [
    {
        id:1,
        label:'UserName',
        type:'text',
        placeholder:'John_doe'
    },
    {
        id:2,
        label:'Name and surName',
        type:'text',
        placeholder:'John_doe'
    },
    {
        id:3,
        label:'Email',
        type:'text',
        placeholder:'John_doe'
    },
    {
        id:4,
        label:'Phone',
        type:'text',
        placeholder:'John_doe'
    },
    {
        id:5,
        label:'Address',
        type:'text',
        placeholder:'John_doe'
    },
    {
        id:6,
        label:'Country',
        type:'text',
        placeholder:'John_doe'
    },
]

export const productInputs= [
    {
        id:1,
        label:'Title',
        type:'text',
        placeholder:'Apple Macbook Pro'
    },
    {
        id:2,
        label:'Discription',
        type:'text',
        placeholder:'Description'
    },
    {
        id:3,
        label:'Category',
        type:'text',
        placeholder:'Computers'
    },
    {
        id:4,
        label:'Prize',
        type:'text',
        placeholder:'100'
    },
    {
        id:5,
        label:'Stock',
        type:'text',
        placeholder:'in stock'
    },
]